name: BeforeAndAfter
options:
  bundleIdPrefix: com.matsuchiyo
  deploymentTarget:
    iOS: "13.2"
targets:
  BeforeAndAfter:
    platform: iOS
    type: application
    sources: [BeforeAndAfter]
    dependencies: 
      - carthage: Realm
      - carthage: RealmSwift
    settings:
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1.0.1
    scheme:
      testTargets:
        - BeforeAndAfterTests
        - BeforeAndAfterUITests
  BeforeAndAfterTests:
    platform: iOS
    type: bundle.unit-test
    sources: [BeforeAndAfterTests]
    dependencies:
      - target: BeforeAndAfter
  BeforeAndAfterUITests:
    platform: iOS
    type: bundle.ui-testing
    sources: [BeforeAndAfterUITests]
    dependencies:
      - target: BeforeAndAfter
