name: BeforeAndAfter
options:
  bundleIdPrefix: com.matsuchiyo
  deploymentTarget:
    iOS: "13.2"
configs:
  Develop_Debug: debug
  Production_Debug: debug
  Develop_Release: release
  Production_Relase: release
targets:
  BeforeAndAfter:
    platform: iOS
    type: application
    sources: [BeforeAndAfter]
    dependencies: 
      - carthage: Realm
      - carthage: RealmSwift
      - framework: Carthage/Build/iOS/FIRAnalyticsConnector.framework
        embed: false
      - framework: Carthage/Build/iOS/Firebase.framework
        embed: false
        link: false
      - framework: Carthage/Build/iOS/FirebaseAnalytics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCore.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCoreDiagnostics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCrashlytics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseInstallations.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleAppMeasurement.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleDataTransport.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleDataTransportCCTSupport.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleUtilities.framework
        embed: false
      - framework: Carthage/Build/iOS/nanopb.framework
        embed: false
      - framework: Carthage/Build/iOS/PromisesObjC.framework
        embed: false
      - framework: Carthage/Build/iOS/Realm.framework
        embed: false
      - framework: Carthage/Build/iOS/RealmSwift.framework
        embed: false
    settings:
      MARKETING_VERSION: 1.0.1
      CURRENT_PROJECT_VERSION: 1.0.2
      OTHER_LDFLAGS: $(OTHER_LDFRAGS) -ObjC
    scheme:
      testTargets:
        - BeforeAndAfterTests
        - BeforeAndAfterUITests
      configVariants:
        - Develop
        - Production
  BeforeAndAfterTests:
    platform: iOS
    type: bundle.unit-test
    sources: [BeforeAndAfterTests]
    dependencies:
      - target: BeforeAndAfter
  BeforeAndAfterUITests:
    platform: iOS
    type: bundle.ui-testing
    sources: [BeforeAndAfterUITests]
    dependencies:
      - target: BeforeAndAfter
