name: BeforeAndAfter
options:
  bundleIdPrefix: com.matsuchiyo
  deploymentTarget:
    iOS: "13.2"
configs:
  Develop_Debug: debug
  Production_Debug: debug
  Develop_Release: release
  Production_Release: release
targets:
  BeforeAndAfter:
    platform: iOS
    type: application
    sources: [BeforeAndAfter]
    dependencies: 
      - carthage: Realm
      - carthage: RealmSwift
      - framework: Carthage/Build/iOS/FIRAnalyticsConnector.framework
        embed: false
      - framework: Carthage/Build/iOS/Firebase.framework
        embed: false
        link: false
      - framework: Carthage/Build/iOS/FirebaseAnalytics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCore.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCoreDiagnostics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCrashlytics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseInstallations.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleAppMeasurement.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleDataTransport.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleDataTransportCCTSupport.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleUtilities.framework
        embed: false
      - framework: Carthage/Build/iOS/nanopb.framework
        embed: false
      - framework: Carthage/Build/iOS/PromisesObjC.framework
        embed: false
      - framework: Carthage/Build/iOS/Realm.framework
        embed: false
      - framework: Carthage/Build/iOS/RealmSwift.framework
        embed: false
    settings:
      base:
        MARKETING_VERSION: 1.0.1
        CURRENT_PROJECT_VERSION: 1.0.2
        OTHER_LDFLAGS: $(OTHER_LDFRAGS) -ObjC
        PRODUCT_BUNDLE_IDENTIFIER: com.matsuchiyo.BeforeAndAfter
      configs:
        Develop_Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.matsuchiyo.BeforeAndAfter.Develop
        Develop_Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.matsuchiyo.BeforeAndAfter.Develop
    scheme:
      testTargets:
        - BeforeAndAfterTests
        - BeforeAndAfterUITests
      configVariants:
        - Develop
        - Production
    postBuildScripts:
      - path: BeforeAndAfter/copy_google_service_info_plist.sh
        name: Copy GoogleService-Info.plist
  BeforeAndAfterTests:
    platform: iOS
    type: bundle.unit-test
    sources: [BeforeAndAfterTests]
    dependencies:
      - target: BeforeAndAfter
  BeforeAndAfterUITests:
    platform: iOS
    type: bundle.ui-testing
    sources: [BeforeAndAfterUITests]
    dependencies:
      - target: BeforeAndAfter
